# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 604ac7c96bce1204bca95e5310e8889399365bc42b3276aa3339f734113f3e9c9f0215721fe4618389ce2251a9f52ae0f55aadbb4053d1fb9d08425ee793d2be

test:
  secret_key_base: cc214f128852989279e10015b77a0ecc48ac4697aeda4ce4b1333e2e6b3981472c3fa4148d922e525436068da62756c8fb795ecdf55ed1bec5ad838a6df63a8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
